// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaU0p99QxGh5ct04_USGEsnBgii3zD5g4',
    appId: '1:831140350240:web:a54dd20c0dbe102b9fef45',
    messagingSenderId: '831140350240',
    projectId: 'circlebook-6963b',
    authDomain: 'circlebook-6963b.firebaseapp.com',
    storageBucket: 'circlebook-6963b.appspot.com',
    measurementId: 'G-WFVWKKQT0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnF0m2eXpJN3gWAXN3sA8FNftTK1BPyvA',
    appId: '1:831140350240:android:6d7a1d665e992c759fef45',
    messagingSenderId: '831140350240',
    projectId: 'circlebook-6963b',
    storageBucket: 'circlebook-6963b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOLJ3fz2qgSuxydjDtHVyp8Typ5aPkCNc',
    appId: '1:831140350240:ios:1cb069c0d208edaf9fef45',
    messagingSenderId: '831140350240',
    projectId: 'circlebook-6963b',
    storageBucket: 'circlebook-6963b.appspot.com',
    iosClientId: '831140350240-fjpnvmvqaj2dupvgrqhl958lsj9ihgnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.circlebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOLJ3fz2qgSuxydjDtHVyp8Typ5aPkCNc',
    appId: '1:831140350240:ios:1cb069c0d208edaf9fef45',
    messagingSenderId: '831140350240',
    projectId: 'circlebook-6963b',
    storageBucket: 'circlebook-6963b.appspot.com',
    iosClientId: '831140350240-fjpnvmvqaj2dupvgrqhl958lsj9ihgnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.circlebook',
  );
}
